### ISSUE TITLE
Unity2019.3.0f3でUnitypackageを読み込んだときにNullReferenceExceptionが出る

### ISSUE THREAD

**Issue by matsuvr** [negipoyoc/Voiceer#3]
以下、エラーメッセージです

NullReferenceException: Object reference not set to an instance of an object
Voiceer.SoundPlayer.PlaySound (Voiceer.Hook hook) (at Assets/Voiceer/Editor/Scripts/SoundPlayer.cs:40)
Voiceer.EditorHook+CompileFinishHook+<>c.<.cctor>b__0_0 () (at Assets/Voiceer/Editor/Scripts/EditorHook.cs:71)
UnityEditor.EditorApplication.Internal_CallDelayFunctions () (at <83a73882c51c4602b3d34743827d03e7>:0)

**Comment by ookumaneko** [comment]
すみません、Pull Requestのやり方よく理解してないので、とりあえず解決策を書いておきます。
SoundPlayer.csの28行目からの所を下記に置き換えたら2019.2.17では動いたので、2019.3でも動くかも知れません

`            var unityEditorAssembly = typeof(AudioImporter).Assembly;
            var audioUtilClass = unityEditorAssembly.GetType("UnityEditor.AudioUtil");
            var method = audioUtilClass.GetMethod
            (
                "PlayClip",
                BindingFlags.Static | BindingFlags.Public,
                null,
#if UNITY_2019_2_OR_NEWER
                new System.Type[] { typeof(AudioClip), typeof(int), typeof(bool) },
#else
                new Type[] { typeof(AudioClip) },
#endif
                null
            );

#if UNITY_2019_2_OR_NEWER
            method.Invoke(null, new object[] { clip, 0, false });
#else
            method.Invoke(null, new object[] {clip});
#endif`

**Comment by negipoyoc** [comment]
↑で修正できました😊ありがとうございます！
